[package]
name = "nargo-mcp"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
description = "Nargo model context protocol"
keywords = ["mcp", "protocol", "nargo"]
categories = ["development-tools"]
repository = "https://github.com/doki-land/nargo/compilers/nargo-mcp"
documentation = "https://docs.rs/nargo-mcp"

[dependencies]
nargo-types.workspace = true
nargo-ir.workspace = true
nargo-parser.workspace = true
nargo-compiler.workspace = true
nargo-lsp.workspace = true
oak-core.workspace = true
oak-lsp.workspace = true
oak-vfs.workspace = true
dashmap.workspace = true
serde.workspace = true

chrono.workspace = true
url.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "sync", "io-util", "time", "io-std"] }
futures.workspace = true
