[package]
name = "nargo-script-analyzer"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
description = "Nargo script analyzer"
keywords = ["script", "analyzer", "nargo"]
categories = ["development-tools"]
repository = "https://github.com/doki-land/nargo/compilers/nargo-script-analyzer"
documentation = "https://docs.rs/nargo-script-analyzer"

[dependencies]
nargo-types.workspace = true
nargo-ir.workspace = true
serde_json.workspace = true
