//! Nargo MCP Resources
//!
//! This module defines and implements all the resources available through
//! the Nargo MCP server for accessing project configuration and metadata.

use crate::types::{Resource, ResourceContents};
use oak_json;

/// Returns all available Nargo resources.
///
/// Each resource provides access to specific project information.
///
/// # Available Resources
///
/// - `nargo://config` - Nargo.toml configuration file
/// - `nargo://lock` - Nargo.lock lock file
/// - `nargo://manifest` - Project manifest (JSON)
/// - `nargo://dependencies` - Dependencies list
/// - `nargo://scripts` - Available scripts
/// - `nargo://workspace` - Workspace information
/// - `nargo://target/tree` - Build artifacts structure
pub fn get_nargo_resources() -> Vec<Resource> {
    vec![
        Resource {
            uri: "nargo://config".to_string(),
            name: "Nargo.toml 配置".to_string(),
            description: Some("项目配置文件内容".to_string()),
            mime_type: Some("text/toml".to_string()),
        },
        Resource {
            uri: "nargo://lock".to_string(),
            name: "Nargo.lock 锁文件".to_string(),
            description: Some("依赖锁定文件".to_string()),
            mime_type: Some("text/toml".to_string()),
        },
        Resource {
            uri: "nargo://manifest".to_string(),
            name: "项目清单".to_string(),
            description: Some("项目元数据和依赖信息".to_string()),
            mime_type: Some("application/json".to_string()),
        },
        Resource {
            uri: "nargo://dependencies".to_string(),
            name: "依赖列表".to_string(),
            description: Some("所有依赖及其版本信息".to_string()),
            mime_type: Some("application/json".to_string()),
        },
        Resource {
            uri: "nargo://scripts".to_string(),
            name: "脚本列表".to_string(),
            description: Some("可用的 npm 脚本".to_string()),
            mime_type: Some("application/json".to_string()),
        },
        Resource {
            uri: "nargo://workspace".to_string(),
            name: "工作区信息".to_string(),
            description: Some("工作区成员和结构".to_string()),
            mime_type: Some("application/json".to_string()),
        },
        Resource {
            uri: "nargo://target/tree".to_string(),
            name: "构建产物结构".to_string(),
            description: Some("/target 目录结构和产物信息".to_string()),
            mime_type: Some("application/json".to_string()),
        },
    ]
}

/// Reads a resource by URI.
///
/// # Arguments
///
/// * `uri` - The URI of the resource to read.
///
/// # Returns
///
/// Result containing the resource contents or an error message.
pub fn read_nargo_resource(uri: &str) -> Result<ResourceContents, String> {
    match uri {
        "nargo://config" => Ok(ResourceContents {
            uri: uri.to_string(),
            mime_type: Some("text/toml".to_string()),
            text: Some(
                r#"[package]
name = "my-project"
version = "0.1.0"
edition = "2024"
authors = ["Your Name <you@example.com>"]

[dependencies]
react = "18.2.0"
lodash = { version = "4.17.21", features = ["es"] }

[dev-dependencies]
vitest = "1.0.0"

[scripts]
dev = "nargo run --watch"
build = "nargo build --release"
test = "nargo test"

[features]
default = ["ssr"]
ssr = []
"#
                .to_string(),
            ),
            blob: None,
        }),
        "nargo://lock" => Ok(ResourceContents {
            uri: uri.to_string(),
            mime_type: Some("text/toml".to_string()),
            text: Some(
                r#"# This file is automatically @generated by Nargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "react"
version = "18.2.0"
source = "registry+https://registry.npmjs.org"
checksum = "sha256-abc123..."

[[package]]
name = "lodash"
version = "4.17.21"
source = "registry+https://registry.npmjs.org"
checksum = "sha256-def456..."
"#
                .to_string(),
            ),
            blob: None,
        }),
        "nargo://manifest" => Ok(ResourceContents {
            uri: uri.to_string(),
            mime_type: Some("application/json".to_string()),
            text: Some(
                oak_json::to_string_pretty(&serde_json::json!({
                    "name": "my-project",
                    "version": "0.1.0",
                    "edition": "2024",
                    "dependencies": {
                        "react": "18.2.0",
                        "lodash": "4.17.21"
                    },
                    "devDependencies": {
                        "vitest": "1.0.0"
                    },
                    "scripts": {
                        "dev": "nargo run --watch",
                        "build": "nargo build --release",
                        "test": "nargo test"
                    }
                }))
                .map_err(|e| e.to_string())?,
            ),
            blob: None,
        }),
        "nargo://dependencies" => Ok(ResourceContents {
            uri: uri.to_string(),
            mime_type: Some("application/json".to_string()),
            text: Some(
                oak_json::to_string_pretty(&serde_json::json!({
                    "production": [
                        {
                            "name": "react",
                            "version": "18.2.0",
                            "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz",
                            "integrity": "sha256-abc123..."
                        },
                        {
                            "name": "lodash",
                            "version": "4.17.21",
                            "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
                            "integrity": "sha256-def456..."
                        }
                    ],
                    "development": [
                        {
                            "name": "vitest",
                            "version": "1.0.0",
                            "resolved": "https://registry.npmjs.org/vitest/-/vitest-1.0.0.tgz",
                            "integrity": "sha256-ghi789..."
                        }
                    ]
                }))
                .map_err(|e| e.to_string())?,
            ),
            blob: None,
        }),
        "nargo://scripts" => Ok(ResourceContents {
            uri: uri.to_string(),
            mime_type: Some("application/json".to_string()),
            text: Some(
                oak_json::to_string_pretty(&serde_json::json!({
                    "scripts": [
                        {
                            "name": "dev",
                            "command": "nargo run --watch",
                            "description": "启动开发服务器"
                        },
                        {
                            "name": "build",
                            "command": "nargo build --release",
                            "description": "构建生产版本"
                        },
                        {
                            "name": "test",
                            "command": "nargo test",
                            "description": "运行测试"
                        }
                    ]
                }))
                .map_err(|e| e.to_string())?,
            ),
            blob: None,
        }),
        "nargo://workspace" => Ok(ResourceContents {
            uri: uri.to_string(),
            mime_type: Some("application/json".to_string()),
            text: Some(
                oak_json::to_string_pretty(&serde_json::json!({
                    "root": "/path/to/workspace",
                    "members": [
                        {
                            "name": "core",
                            "path": "packages/core",
                            "version": "0.1.0"
                        },
                        {
                            "name": "cli",
                            "path": "packages/cli",
                            "version": "0.1.0"
                        },
                        {
                            "name": "web",
                            "path": "apps/web",
                            "version": "0.1.0"
                        }
                    ],
                    "sharedDependencies": ["react", "lodash"]
                }))
                .map_err(|e| e.to_string())?,
            ),
            blob: None,
        }),
        "nargo://target/tree" => Ok(ResourceContents {
            uri: uri.to_string(),
            mime_type: Some("application/json".to_string()),
            text: Some(
                oak_json::to_string_pretty(&serde_json::json!({
                    "target": {
                        "debug": {
                            "size": "125MB",
                            "artifacts": [
                                "index.js",
                                "index.css",
                                "assets/",
                                ".nargo-cache/"
                            ]
                        },
                        "release": {
                            "size": "45MB",
                            "artifacts": [
                                "index.js",
                                "index.css",
                                "assets/"
                            ]
                        }
                    }
                }))
                .map_err(|e| e.to_string())?,
            ),
            blob: None,
        }),
        _ => Err(format!("Unknown resource URI: {}", uri)),
    }
}
