[package]
name = "nargo-hooks"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
description = "Nargo hooks system"
keywords = ["hooks", "nargo"]
categories = ["development-tools"]
repository = "https://github.com/doki-land/nargo/compilers/nargo-hooks"
documentation = "https://docs.rs/nargo-hooks"

[dependencies]
nargo-types.workspace = true
nargo-config.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
